### ISSUE TITLE
Some observations that failed:

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [zoho/hawking#10]
**Note : All timezones are set to IST.  And tested on 08-04-2021 (Thrusday IST)**  

Input : "there was a conference day before yesterday" 
Output -> "endDateFormat": "2021-04-08T05:29:59" (Failed)

Input : "there will be a conference from today till next monday"  
Output -> "startDateFormat": "2021-04-12T05:30:00", "endDateFormat": "2021-04-13T05:29:59" (Failed for start date)

Input : "there will be a conference today and  next friday" (there is 2 spaces between "and" and "next")
Output : "startDateFormat": "2021-04-16T05:30:00",  "endDateFormat": "2021-04-17T05:29:59" (Failed for start date)

Could you please help me out in these?

**Comment by ArulVendhan** [comment]
we are working on the issues. will update once fixed

**Comment by ArulVendhan** [comment]
we have analyzed the cases,

Hawking Time parser works well for input sentences more in structural English as it is trained that way, we will be handling cases that used in chats and speakable format(the direct way of input that lacks grammar yet meaningful).

**=>** Using prepositions at the required place will give expected results.
Input 1: There was a conference **on** day before yesterday

**=>** Usage of multiple prepositions have related words in English like the following
"from today to next Monday"
"from today until next Monday"

**from** and **till** are least likely used in English together.  We will handle these cases in the upcoming releases. To get the expected result use (from, to) or (from, until) words together. 
Input 2: "there will be a conference from today until next Monday"

**=>** We have solved the multiple spacing Issue. It will be available in master soon and next maven Release 

**=>** And let us know the timezone of the server/machine you are running the code. As you set "IST" as the required output format the start_date and end_date will be altered based on server/machine time zone.

**Sample Input :** 
"Good morning, Have a nice day. there will be conference on 12/12/2021"
 **hawkingConfiguration.setTimeZone("PST")** ===> Input Timezone Configuration 

 **Output Log:**
INFO: Label : D
Text : on 12/12/2021
IsTimeZonePresent : false
**Time Zone : -07:00**  =====> This represents configured timeZone (PST is now on Daylight saving so -7:00)
IsExactTimePresent : false
Id : 0
End Index : 69
Start Index : 56
Match Type : 
Start : 2021-12-12T12:30:00.000**+05:30** =====> This represents Server/machine timezone
End : 2021-12-13T12:29:59.000**+05:30** =====> This represents Server/machine timezone
Sequence :SINGLE
Expression :(0)

**Comment by ShoubhikBanerjee** [comment]
Thanx for the explanation @ArulVendhan .

I have one more test case, of you won't mind :)

Input =>  "Hi, I couldn't attend seminar on 10th February 2021 (Wednesday) due to some reason." 

Output => "startDateFormat": "2022-02-10T05:30:00",  "endDateFormat": "2022-02-11T05:29:59".
Here it is failing to handle the tense. 

Could you please check this too ?

Thank You.

**Comment by ArulVendhan** [comment]
Yes @ShoubhikBanerjee 
Could you please pull the latest changes from the master and check it once again. We have updated Tense cases recently.
Seems working fine for the input case you have given
**Output Log:**
INFO: Label : D
Text : 10th February 2021
IsTimeZonePresent : false
Time Zone : +05:30
IsExactTimePresent : false
Id : 0
End Index : 51
Start Index : 33
Match Type : 
Start : 2021-02-10T00:00:00.000+05:30
End : 2021-02-10T23:59:59.000+05:30
Sequence :SINGLE
Expression :(0)

**Comment by ArulVendhan** [comment]
You can use the latest maven import as well to check if this working 
check ReadMe.md for that.

**Comment by ShoubhikBanerjee** [comment]
Hi @ArulVendhan , I have checked it with latest maven repo, and the issue for "tense" is fixed, thanx for it. 

But it also detects the "(Wednesday)" i.e. in bracket and detects the last Wednesday (i.e  "startDateFormat": "2021-04-14T05:30:00", ).

Any suggestions for it ?

**Comment by ArulVendhan** [comment]
Sure @ShoubhikBanerjee will check and update
