### ISSUE TITLE
Cannot parse: "10/28/2021" or "10-28-2021"

### ISSUE THREAD

**Issue by deltaGPhys** [zoho/hawking#25]
It seems like it should be able to parse these - maybe not?

**Comment by ArulVendhan** [comment]
Hi @deltaGPhys,
The default date format is "dd/mm/yyyy" and "yyyy/mm/dd"

you can configure date format for your case like this,
hawkingConfiguration.setDateFormat("mm/dd/yyyy") 
it will accept these 6 date format "10/28/2021", "10-28-2021", "10.28.2021", "2021/28/10", "2021-28-10", "2021.28.10"
 
Hawking time parser supports 20+ ISO standard date formats with these 3 seperators "**./-**" , you can configure them using hawking configuration as required. 

Kindly Reach out for any clarifications.

**Comment by ajar19** [comment]
Please contact us if you need more information on this. Closing this for now.
