### ISSUE TITLE
Is there a non-GPL3 option

### ISSUE THREAD

**Issue by mikehearn** [zoho/hawking#26]
Although the docs say that the library is great for business apps, GPL3 isn't that useful for them. Does Zoho sell commercial licenses or otherwise provide some way to get a non-GPL3 version of the library?

**Comment by ArulVendhan** [comment]
Hi @mikehearn,
Hawking Date Time Parser uses Stanford corenlp 4.2.0, which is [GNU General Public License](http://www.gnu.org/licenses/gpl.html) v3, Parser layer to find dates is built of Stanford Corenlp, we can't remove it. So non-GPL version is not possible.
