### ISSUE TITLE
One day difference

### ISSUE THREAD

**Issue by madukan** [zoho/hawking#40]
I was trying to get a date range based on the given example in the readme file in Hawking library.

My code: 

```
        HawkingTimeParser parser = new HawkingTimeParser();
        String inputText = "Good morning, Have a nice day. Shall we meet on December 20 between 8 and 9 am ?";
        Date referenceDate = new Date();
        HawkingConfiguration hawkingConfiguration = new HawkingConfiguration();
        DatesFound datesFound = parser.parse(inputText, referenceDate, hawkingConfiguration, "eng");

        for (ParserOutput dateGroup : datesFound.getParserOutputs()) {
            System.out.println(dateGroup.getDateRange().getStart());
            System.out.println(dateGroup.getDateRange().getEnd());
        }
```

Expected:

```
2024-12-20T01:08:00.000+11:00
2024-12-20T10:09:00.000+11:00
```

Actual:

```
2024-12-20T01:00:00.000+11:00
2024-12-21T00:59:59.000+11:00
2024-12-20T10:00:00.000+11:00
2024-12-20T10:00:00.000+11:00
```

Any ideas why this may be happening or how I can overcome the issue?

**Comment by ArulVendhan** [comment]
Hi @madukan , 
For the given text "Good morning, Have a nice day. Shall we meet on December 20 between 8 and 9 am ?", 
Hawking extracted 2 date texts 
`1) " on December 20 between 8", 
2) "and 9 am"`

The response was expected as you mentioned, except for the time. 
2024-12-20T08:00:00.000+11:00
2024-12-20T09:00:00.000+11:00

In the current hawking version, **"am"** mentioned in the 2nd date text could not be mapped to the 1st date text, so the entire day is given as output. 

so try  with *"am"* mentioned for both time texts like this 
`Shall we meet on December 20 between 8 am and 9 am ?`

For this input response would be (Note: My machine is running in IST and no Daylight saving time here)
id : 0
text: " on December 20 between 8"
Start: 2024-12-20T08:00:00.000+05:30
End: 2024-12-20T08:00:00.000+05:30

Id: 1
Text: and 9 am
Start: 2024-12-20T09:00:00.000+05:30
End: 2024-12-20T09:00:00.000+05:30

Sequence: MULTIPLE
Expression :(0)between(1)

So here the key "Sequence" is used to understand whether the date/time is a single or multiple date/time. Using this key and the next key "Expression" user can relate both dates using ID and arrive at the date as needed from the response. 

Kindly reach us for any further clarifications needed.
