### ISSUE TITLE
A couple of things don't seem quite right

### ISSUE THREAD

**Issue by MattRiddell** [zoho/hawking#9]
A few I tested:

next Wednesday - correct
next Wednesday morning - **incorrect** (adds a day)
next Wednesday before 3pm - **no response**
Tomorrow morning - **incorrect** (adds a day)
Tomorrow afternoon - **incorrect** (adds a day)
Tomorrow at 3pm - correct
yesterday evening - correct
yesterday morning - **incorrect** - becomes today?
later this week - **incorrect** - puts next week

I used timezone EST for all of these but the docker library was likely running UTC. Not sure if the docker machine should be in the user or server timezone.

Is there somewhere you'd recommend I start looking?

**Comment by MattRiddell** [comment]
Ok, I changed the config to UTC for the timezone and end up with:

next Wednesday - correct
next Wednesday morning - **incorrect (adds a day)**
next Wednesday before 3pm - **no response**
Tomorrow morning - **incorrect (adds a day)**
Tomorrow afternoon - **_now correct_**
Tomorrow at 3pm - correct
yesterday evening - correct
yesterday morning - **incorrect** - becomes today?
later this week - **incorrect** - puts next week

**Comment by ajar19** [comment]
We are not able to replicate this issue in our setup.
It looks like some issue with the timezone settings. 
We will try with various timezone settings and check whether we are able to replicate this. 

We will get back to you with an update soon.

**Comment by MattRiddell** [comment]
Hmmm ok, I'll pull my copy out of docker and drop the springboot api as well to see if I can replicate it without those pieces and I'll revert back to you.

**Comment by MattRiddell** [comment]
In a fresh fork doing:

`String inputText = "let's meet next Wednesday morning";`

and

`hawkingConfiguration.setTimeZone("ETC");`

I get:

```zsh
❯  /usr/bin/env "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java" -Dfile.encoding=UTF-8 -cp /var/folders/_b/9pvskwhs3vx877rtp6z08k0r0000gn/T/cp_7o3e0tlvjkryzy68t71yfsv08.jar com.zoho.hawking.HawkingDemo
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 08, 2021 8:15:44 AM com.zoho.hawking.language.english.Parser getCRFInstance
INFO: Loading Parser Model
Apr 08, 2021 8:15:45 AM com.zoho.hawking.language.english.Parser getCRFInstance
INFO: Parser Model Loaded
Apr 08, 2021 8:15:45 AM com.zoho.hawking.language.english.Recognizer recognize
INFO: Recoginzer Regex Tagged Sequence::::<implict_prefix>next</implict_prefix> <day_of_week>wednesday</day_of_week> <part_of_day>morning</part_of_day>:::::
Apr 08, 2021 8:15:46 AM com.zoho.hawking.HawkingTimeParser parse
INFO: Label : D
Text : next Wednesday morning
IsTimeZonePresent : false
Time Zone : +00:00
IsExactTimePresent : false
Id : 0
End Index : 33
Start Index : 11
Match Type : 
Start : 2021-04-15T01:00:00.000-05:00
End : 2021-04-15T03:59:59.000-05:00
Sequence :SINGLE
Expression :(0)
```

**Comment by ArulVendhan** [comment]
Hi MattRiddell,
We have found the issue, it is not because of the timezone. we have updated the fix in Master. pull the latest changes. if you are using maven dependency, these changes will be available in next release 0.1.1 soon. 

Other issue "later this week" will be handled and will update here .

**Comment by MattRiddell** [comment]
Ok great will do

**Comment by ArulVendhan** [comment]
we will update the "later this week"  case in enhancements and will add it in the release description. As other mentioned issues are solved, closing this issue.
